<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [45]:
import numpy as np

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [46]:
array_1d = np.arange(10)
print(f"El array unidimensional creado a partir del método np.arange(): \n  {array_1d} \n")

El array unidimensional creado a partir del método np.arange(): 
  [0 1 2 3 4 5 6 7 8 9] 



#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [47]:
array_2d = array_1d.reshape(2, 5)
print(f"El array bidimensional creado a partir del método np.reshape(): \n  {array_2d} \n")

El array bidimensional creado a partir del método np.reshape(): 
  [[0 1 2 3 4]
 [5 6 7 8 9]] 



#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [48]:
# Ejemplo
array = np.array([0, 2, 0, 3, 0, 4, 0])

# Encontrar índices de elementos con valor distinto de 0
indices_no_cero = np.nonzero(array)
print(f"Los índices con valor distinto a 0 son: \n  {indices_no_cero} \n")


Los índices con valor distinto a 0 son: 
  (array([1, 3, 5]),) 



#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [49]:
array_3x3_random = np.random.rand(3, 3)
print(f"El array 3x3 con valores aleatorios entre 0 y 1 es : \n  {array_3x3_random} \n")

El array 3x3 con valores aleatorios entre 0 y 1 es : 
  [[0.04739777 0.4855401  0.86657653]
 [0.59168347 0.37830777 0.84061728]
 [0.87010475 0.32020629 0.56513552]] 



#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [54]:
# Crear un array de 10 números aleatorios
array_random = np.random.rand(10)

# Encontrar el valor máximo y mínimo
valor_maximo = np.max(array_random)
valor_minimo = np.min(array_random)

print(f"El array de 10 números aleatorios es \n {array_random}")
print(f"El valor máximo del array es {valor_maximo}")
print(f"El valor mínimo del array es {valor_minimo}")

El array de 10 números aleatorios es 
 [0.36995716 0.80521258 0.71253883 0.82820612 0.94371159 0.27164952
 0.68582922 0.14163922 0.8434908  0.84228419]
El valor máximo del array es 0.9437115927342232
El valor mínimo del array es 0.1416392232348791


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [55]:
# Crear un array de una dimensión
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Invertir el array
array_invertido = array_1d[::-1]
print(f"El array_1d invertido es : \n  {array_invertido} \n")

El array_1d invertido es : 
  [10  9  8  7  6  5  4  3  2  1] 




#### Ejercicio 7 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [56]:
array_3d = np.arange(1, 25).reshape(2, 3, 4)
array_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [57]:
# Seleccionar el primer valor igual a 15 en el array
index_15 = np.argwhere(array_3d == 15)[0]
index_15

array([1, 0, 2])

In [58]:
# Seleccionar todos los elementos del primer array
primer_array = array_3d[0]
primer_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
# Seleccionar la última fila del último array
ultima_fila_array_3d = array_3d[-1, -1]
ultima_fila_array_3d

array([21, 22, 23, 24])


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [60]:
array_3d_v2 = np.arange(1, 31).reshape(3, 2, 5)
array_3d_v2

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [61]:
# Seleccionar el subarray que contiene los dos primeros elementos de cada fila del primer array
subarray = array_3d_v2[0, :, :2]
subarray

array([[1, 2],
       [6, 7]])

In [62]:
# Seleccionar el subarray que contiene todas las filas de los dos últimos arrays
subarray_dos_ultimos = array_3d_v2[1:, :, :]
subarray_dos_ultimos

array([[[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

#### Ejercicio 9 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [63]:
array_3d_v3 = np.arange(1, 25).reshape(4, 3, 2)
array_3d_v3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [64]:
# Cambiar todos los elementos de la segunda fila del segundo array por 0
array_3d_v3[1, 1, :] = 0
array_3d_v3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 0,  0],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [65]:
# Cambiar todos los valores del último array a -1
array_3d_v3[-1, :, :] = -1
array_3d_v3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 0,  0],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]])


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [66]:
array_3d_range = np.arange(-10, 14).reshape(2, 4, 3)
array_3d_range

array([[[-10,  -9,  -8],
        [ -7,  -6,  -5],
        [ -4,  -3,  -2],
        [ -1,   0,   1]],

       [[  2,   3,   4],
        [  5,   6,   7],
        [  8,   9,  10],
        [ 11,  12,  13]]])

In [67]:
# Seleccionar todos los elementos mayores a 5
elementos_mayores_5 = array_3d_range[array_3d_range > 5]
elementos_mayores_5

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [68]:
# Reemplazar todos los elementos negativos por 0
array_3d_range[array_3d_range < 0] = 0
array_3d_range

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  1]],

       [[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]]])

#### Ejercicio 11 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [69]:
array_3d_new = np.arange(1, 28).reshape(3, 3, 3)
array_3d_new

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [70]:
# Seleccionar el subarray del segundo array que contenga solo las dos primeras columnas
subarray_segundo_array = array_3d_new[1, :, :2]
subarray_segundo_array

array([[10, 11],
       [13, 14],
       [16, 17]])

In [71]:
# Seleccionar todos los elementos del tercer array que sean mayores que 20
elementos_mayores_20_tercer_array = array_3d_new[2, :, :][array_3d_new[2, :, :] > 20]
elementos_mayores_20_tercer_array

array([21, 22, 23, 24, 25, 26, 27])

#### Ejercicio 12 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [78]:
# Crear un array de 10 números aleatorios
array_random = np.random.rand(10)

# Reemplazar los valores máximos y mínimos por 0
array_random[array_random == np.max(array_random)] = 0
array_random[array_random == np.min(array_random)] = 0
print(f"El array de 10 números aleatorios es:\n{array_random}")

El array de 10 números aleatorios es:
[0.56981536 0.01326348 0.21183895 0.4307123  0.         0.28456385
 0.40437364 0.12985388 0.5714909  0.57531428]


#### Ejercicio 13 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [82]:
# Generar un array de 15 números aleatorios enteros entre 1 y 100
array_random_integers = np.random.randint(1, 101, 15)

# Reordenar el array en orden ascendente
array_ordenado = np.sort(array_random_integers)
 
print(f"El array de 15 números aleatorios es: {array_random_integers}")
print(f"El array ordenado es: {array_ordenado}")

El array de 15 números aleatorios es: [47 48  8  8 43 53 81 60 35 66 69 52 55 73 55]
El array ordenado es: [ 8  8 35 43 47 48 52 53 55 55 60 66 69 73 81]


#### Ejercicio 14 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [84]:
# Crear una matriz 4x4 de valores aleatorios enteros entre 1 y 10
matriz_4x4 = np.random.randint(1, 11, (4, 4))

# Calcular la suma de los elementos a lo largo de las filas y columnas
suma_filas = np.sum(matriz_4x4, axis=1)
suma_columnas = np.sum(matriz_4x4, axis=0)

print(f"La matriz 4x4 es: \n {matriz_4x4}")
print(f"La suma de los elementos a lo largo de las filas es {suma_filas}")
print(f"La suma de los elementos a lo largo de las columnas es {suma_columnas}")

La matriz 4x4 es: 
 [[ 4  5  3  6]
 [ 9  5  9  6]
 [10  1  4  1]
 [ 1  5  9  9]]
La suma de los elementos a lo largo de las filas es [18 29 16 24]
La suma de los elementos a lo largo de las columnas es [24 16 25 22]


#### Ejercicio 15 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [85]:
# Crear una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0
matriz_5x5 = np.ones((5, 5), dtype=int)
matriz_5x5[1:-1, 1:-1] = 0
matriz_5x5

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### Ejercicio 16 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [86]:
# Crear un array de 10 números aleatorios
array_aleatorio = np.random.rand(10)

# Calcular la media y la desviación estándar
media = np.mean(array_aleatorio)
desviacion_estandar = np.std(array_aleatorio)

print(f"El array de 10 númetos aleatorios es {array_aleatorio}")
print(f"La media del array de 1o números aleatorios es {media}")
print(f"La desviación estándar del array de 10 números aleatorios es {desviacion_estandar}")

El array de 10 númetos aleatorios es [0.87555295 0.30602645 0.98021288 0.83073308 0.83128942 0.89510668
 0.42368042 0.054355   0.52303788 0.15598608]
La media del array de 1o números aleatorios es 0.5875980838898383
La desviación estándar del array de 10 números aleatorios es 0.32110476777428276


#### Ejercicio 17 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [87]:
# Generar un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24
array_3d_v4 = np.arange(1, 25).reshape(2, 3, 4)
array_3d_v4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [88]:
# Transponer el array para intercambiar los ejes a la forma (4, 3, 2)
array_transpuesto = np.transpose(array_3d_v4, axes=(2, 1, 0))
array_transpuesto

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

Lo que ha ocurrido es que los índices de los elementos han cambiado de acuerdo con el reordenamiento de los ejes. Par que se entienda mejor:
 
1. Forma original del array (2, 3, 4)
   - El índice 0 hace referencia al número de subarrays o matrices
   - El índice 1 hace referencia a las filas
   - El índice 2 hace referencia a las columnas
    
2. Tranposición (4, 3, 2)
   - Las columnas se convierten en el índice 0, por lo que ahora van a indicar el número de subarrays o matrices que hay
   - Las filas se queden en el índice 1, por tanto no cambian
   - El número de subarrays o matrices se convierte en el índice 2, y ahora va a referenciar las columnas
    
En resumen, lo que ocurre es lo siguiente:
- La columna pasa a ser capa (nº subarrays o matrices)
- La fila se mantiene
- La capa (nº subarrays o matrices) pasa a ser columna 

#### Ejercicio 18 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [89]:
array_3d_v5 = np.arange(1, 25).reshape(3, 4, 2)
array_3d_v5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [90]:
# Transponer el array para intercambiar el primer y segundo eje
array_transpuesto_nuevo = np.transpose(array_3d_new, axes=(1, 0, 2))
array_transpuesto_nuevo

array([[[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]],

       [[ 4,  5,  6],
        [13, 14, 15],
        [22, 23, 24]],

       [[ 7,  8,  9],
        [16, 17, 18],
        [25, 26, 27]]])

#### Ejercicio 19 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [91]:
array_3d_v6 = np.arange(1, 25).reshape(3, 2, 4)
array_3d_v6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [92]:
# Realizar una rotación completa de los ejes para convertir la forma (3, 2, 4) en (4, 3, 2)
array_rotado = np.transpose(array_3d_v6, axes=(2, 0, 1))
array_rotado

array([[[ 1,  5],
        [ 9, 13],
        [17, 21]],

       [[ 2,  6],
        [10, 14],
        [18, 22]],

       [[ 3,  7],
        [11, 15],
        [19, 23]],

       [[ 4,  8],
        [12, 16],
        [20, 24]]])

#### Ejercicio 20 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [93]:
# Crear un array tridimensional de dimensiones (3, 4, 5) con valores enteros aleatorios entre -10 y 10
array_random_3d = np.random.randint(-10, 11, (3, 4, 5))
array_random_3d

array([[[  9,  -8,   8,   9,   2],
        [ -8,   0,   5,   3,  -6],
        [ 10,   4,  -3,   9,   8],
        [ -5,  -3,   9,   7,   5]],

       [[ -1,  -4, -10,   4, -10],
        [  7, -10,  -9,  -9,   2],
        [ -5,   8,   4,   5,  -5],
        [ -6,   8,  -4,   5,   4]],

       [[  8,  -8, -10,  -4,  -8],
        [ 10,  -4,  -5,  -6,   8],
        [ -2,   3,  -2,   6,   9],
        [ -3,  -3,  10,  10,   6]]], dtype=int32)

In [94]:
# Crear un array vacío con la misma forma y dimensiones que el array original
array_resultado = np.empty_like(array_random_3d, dtype=object)

# Calcular la mediana, el máximo y el mínimo del array original
mediana = np.median(array_random_3d)
maximo = np.max(array_random_3d)
minimo = np.min(array_random_3d)

# Reemplazar los valores en el array vacío según las condiciones
for index, value in np.ndenumerate(array_random_3d):
    if value == mediana:
        array_resultado[index] = "M"
    elif value > mediana:
        array_resultado[index] = "X"
    elif value < mediana:
        array_resultado[index] = "Y"
    if value == maximo:
        array_resultado[index] = "MAX"
    if value == minimo:
        array_resultado[index] = "MIN"

print(f"El array tridimensional es {array_random_3d}")
print(f"La mediana del array tridimensional es {mediana}")
print(f"El máximo del array tridimensional es {maximo}")
print(f"El mínimo del array tridimensionalk es {minimo}")
print(f"El resultado del array vacío es {array_resultado}")

El array tridimensional es [[[  9  -8   8   9   2]
  [ -8   0   5   3  -6]
  [ 10   4  -3   9   8]
  [ -5  -3   9   7   5]]

 [[ -1  -4 -10   4 -10]
  [  7 -10  -9  -9   2]
  [ -5   8   4   5  -5]
  [ -6   8  -4   5   4]]

 [[  8  -8 -10  -4  -8]
  [ 10  -4  -5  -6   8]
  [ -2   3  -2   6   9]
  [ -3  -3  10  10   6]]]
La mediana del array tridimensional es 2.0
El máximo del array tridimensional es 10
El mínimo del array tridimensionalk es -10
El resultado del array vacío es [[['X' 'Y' 'X' 'X' 'M']
  ['Y' 'Y' 'X' 'X' 'Y']
  ['MAX' 'X' 'Y' 'X' 'X']
  ['Y' 'Y' 'X' 'X' 'X']]

 [['Y' 'Y' 'MIN' 'X' 'MIN']
  ['X' 'MIN' 'Y' 'Y' 'M']
  ['Y' 'X' 'X' 'X' 'Y']
  ['Y' 'X' 'Y' 'X' 'X']]

 [['X' 'Y' 'MIN' 'Y' 'Y']
  ['MAX' 'Y' 'Y' 'Y' 'X']
  ['Y' 'X' 'Y' 'X' 'X']
  ['Y' 'Y' 'MAX' 'MAX' 'X']]]


#### Ejercicio 21 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [95]:
# Crear un array bidimensional 4x4
matriz_4x4 = np.random.randint(1, 5, (4, 4))

# Verificar si alguna fila es igual a alguna columna
def fila_igual_columna(matriz):
    filas, columnas = matriz.shape
    for i in range(filas):  # Recorrer las filas
        for j in range(columnas):  # Recorrer las columnas
            # Comparar fila i con columna j elemento por elemento
            if all(matriz[i, k] == matriz[k, j] for k in range(filas)):
                return True  # Si coinciden, retornar True
    return False  # Si no se encuentra ninguna coincidencia, retornar False

resultado = fila_igual_columna(matriz_4x4)
print(f"El array bidimensional 4x4 es  \n{matriz_4x4}")
print(f"¿Una fila es exactamente igual a una columna? \n{resultado}")

El array bidimensional 4x4 es  
[[1 4 2 4]
 [4 1 2 2]
 [3 1 2 1]
 [2 1 1 3]]
¿Una fila es exactamente igual a una columna? 
False
